### ISSUE TITLE
404 when opening https://eloquentarduino.github.io/2021/03/tinyml-classification-example-wine-dataset/

### ISSUE THREAD

**Issue by ospilos** [eloquentarduino/eloquentarduino.github.io#1]
Hi Simone,
There seems to be a broken link to the "TinyML classification example: Wine dataset" article. Thankfully it can be retrieved from here, Great tutorial, btw. Many thanks!
Tom

**Comment by eloquentarduino** [comment]
It looks like the whole site was 404 due to a misconfiguration. I solved now, thank you.
